DROP DATABASE IF EXISTS farm_db;

CREATE DATABASE farm_db;

USE farm_db;

CREATE TABLE crop (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cropName VARCHAR(30) UNIQUE NOT NULL,
    growTime INT UNSIGNED NOT NULL,
    irrigation BOOLEAN,
    season VARCHAR(30) NOT NULL
);

CREATE TABLE field (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fieldName VARCHAR(30) UNIQUE NOT NULL,
    acreage INT UNSIGNED NOT NULL,
    note VARCHAR(300) UNIQUE NOT NULL
);